### ISSUE TITLE
Notebook tests

### ISSUE THREAD

**Issue by alex-treebeard** [KyleOS/Data-Analysis#2]
Hey Kyle,

I ran treebeard on a fork of your repo: https://github.com/alex-treebeard/Data-Analysis/runs/1021534834

Looks like you need to regenerate your Pipfile.lock so that missing dependencies are added.

**Comment by KyleOS** [comment]
Hey @alex-treebeard ,

Apologies for the delay - I seem to be running into some dependency issues (on my side). This is a legacy repo though so I'm going to test out treebeard on some others to see how everything works. Thank you for the help!
